/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectakhir;

/**
 *
 * @author hani
 */
public class Makanan extends javax.swing.JFrame {

    /**
     * Creates new form Makanan
     */
    public Makanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RequestMakanan = new javax.swing.JLabel();
        Manis = new javax.swing.JCheckBox();
        jCbxAsam = new javax.swing.JCheckBox();
        jCbxAsin = new javax.swing.JCheckBox();
        jCbxPedas = new javax.swing.JCheckBox();
        jRasa = new javax.swing.JLabel();
        jCbxGurih = new javax.swing.JCheckBox();
        jCbxPahit = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        JTFuang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbxya = new javax.swing.JCheckBox();
        jcbxtidak = new javax.swing.JCheckBox();
        jcbxsehat = new javax.swing.JCheckBox();
        jcbxcs = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbxItalia = new javax.swing.JCheckBox();
        jcbxIndonesia = new javax.swing.JCheckBox();
        china = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampil = new javax.swing.JTextArea();
        jBBackmenu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        vietnam = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RequestMakanan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        RequestMakanan.setText("REKOMENDASI MAKANAN");

        Manis.setText("Manis");
        Manis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManisActionPerformed(evt);
            }
        });

        jCbxAsam.setText("Asam");
        jCbxAsam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxAsamActionPerformed(evt);
            }
        });

        jCbxAsin.setText("Asin");

        jCbxPedas.setText("Pedas");

        jRasa.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jRasa.setText("Request rasa yang diinginkan");

        jCbxGurih.setText("Gurih");

        jCbxPahit.setText("Pahit");
        jCbxPahit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxPahitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel1.setText("Budget uang pelanggan :");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel2.setText("Apakah pelanggan seorang vegetarian");

        jcbxya.setText("Ya");

        jcbxtidak.setText("Tidak");

        jcbxsehat.setText("Makanan Sehat");

        jcbxcs.setText("Makanan Cepat Saji");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel3.setText("pilih makanan sesuai yang diinginkan... (pilih salah satu) :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel4.setText("Asal Negara");

        jcbxItalia.setText("Italia");

        jcbxIndonesia.setText("Indonesia");

        china.setText("China");
        china.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chinaActionPerformed(evt);
            }
        });

        tampil.setColumns(20);
        tampil.setRows(5);
        jScrollPane1.setViewportView(tampil);

        jBBackmenu.setBackground(new java.awt.Color(255, 102, 102));
        jBBackmenu.setText("Menu");
        jBBackmenu.setAutoscrolls(true);
        jBBackmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackmenuActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton1.setText("Pesan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        vietnam.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        vietnam.setText("Vietnam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBBackmenu)
                        .addGap(65, 65, 65)
                        .addComponent(RequestMakanan))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbxcs)
                            .addComponent(jRasa)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTFuang))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Manis)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCbxAsam)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCbxAsin)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCbxPedas)))
                                .addGap(18, 18, 18)
                                .addComponent(jCbxGurih)
                                .addGap(18, 18, 18)
                                .addComponent(jCbxPahit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jcbxya)
                                .addGap(18, 18, 18)
                                .addComponent(jcbxtidak))
                            .addComponent(jcbxsehat)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbxItalia)
                                .addGap(26, 26, 26)
                                .addComponent(jcbxIndonesia)
                                .addGap(18, 18, 18)
                                .addComponent(china)
                                .addGap(18, 18, 18)
                                .addComponent(vietnam))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(RequestMakanan))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBBackmenu)))
                .addGap(18, 18, 18)
                .addComponent(jRasa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manis)
                    .addComponent(jCbxAsam)
                    .addComponent(jCbxAsin)
                    .addComponent(jCbxPedas)
                    .addComponent(jCbxGurih)
                    .addComponent(jCbxPahit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFuang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbxya)
                    .addComponent(jcbxtidak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jcbxsehat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbxcs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxItalia)
                    .addComponent(jcbxIndonesia)
                    .addComponent(china)
                    .addComponent(vietnam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManisActionPerformed
        

    }//GEN-LAST:event_ManisActionPerformed

    private void jCbxAsamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxAsamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbxAsamActionPerformed

    private void jCbxPahitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxPahitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbxPahitActionPerformed

    private void jBBackmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackmenuActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jBBackmenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String show;
        show = "";
        if(jcbxItalia.isSelected()){
            jCbxAsam.isSelected();
            jCbxPedas.isSelected();
            jcbxtidak.isSelected();
            show +="Request Rasa "+Manis.getText()+" "+jCbxAsam.getText();
            show +="\nVegetarian: "+jcbxtidak.getText()+" Termasuk "+jcbxsehat.getText();
            show +="\nRekomendasi Makanan Spaghetti\n";
            show +="Asal Negara "+jcbxItalia.getText()+"\n";
            
        }
        
        else if(jcbxIndonesia.isSelected()){
            jCbxAsam.isSelected();
            jCbxGurih.isSelected();
            jcbxtidak.isSelected();
            show +="Request Rasa "+jCbxAsin.getText()+" "+jCbxAsam.getText()+" "+jCbxGurih.getText();
            show +="\nVegetarian: "+jcbxtidak.getText()+" Termasuk "+jcbxsehat.getText();
            show +="\nRekomendasi Makanan Nasi Goreng\n";  
            show +="Asal Negara "+jcbxIndonesia.getText()+"\n";
        }
        if(china.isSelected()){
            jCbxAsam.isSelected();
            jcbxtidak.isSelected();
            show +="Request Rasa "+Manis.getText()+" "+jCbxAsam.getText();
            show +="\nVegetarian: "+jcbxtidak.getText()+" Termasuk "+jcbxcs.getText();
            show += "\nRekomendasi Makanan Roti Daging\n";
            show +="Asal Negara "+china.getText()+"\n";
        }
        
        else if(vietnam.isSelected()){
            jCbxAsam.isSelected();
            jcbxya.isSelected();
            show +="Request Rasa "+jCbxGurih.getText()+" "+jCbxAsam.getText();
            show +="\nVegetarian: "+jcbxya.getText()+" Termasuk "+jcbxsehat.getText();
            show +="\nRekomendasi Makanan Spring Roll\n";
            show +="Asal Negara "+vietnam.getText()+"\n";
        }
        else{
            
        }
        
        tampil.setText(show);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Makanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFuang;
    private javax.swing.JCheckBox Manis;
    private javax.swing.JLabel RequestMakanan;
    private javax.swing.JCheckBox china;
    private javax.swing.JButton jBBackmenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCbxAsam;
    private javax.swing.JCheckBox jCbxAsin;
    private javax.swing.JCheckBox jCbxGurih;
    private javax.swing.JCheckBox jCbxPahit;
    private javax.swing.JCheckBox jCbxPedas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jRasa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbxIndonesia;
    private javax.swing.JCheckBox jcbxItalia;
    private javax.swing.JCheckBox jcbxcs;
    private javax.swing.JCheckBox jcbxsehat;
    private javax.swing.JCheckBox jcbxtidak;
    private javax.swing.JCheckBox jcbxya;
    private javax.swing.JTextArea tampil;
    private javax.swing.JCheckBox vietnam;
    // End of variables declaration//GEN-END:variables
}
